# -*- coding: utf-8 -*-
"""Hard_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Egydo7xzeus4vZwTFkel8yRflO3qxQoy
"""

!pip -q install librosa soundfile scikit-learn umap-learn matplotlib tqdm sentence-transformers

from google.colab import drive
drive.mount("/content/drive")

import os
AUDIO_ROOT  = "/content/drive/MyDrive/Project Dataset/genres_original"
LYRICS_ROOT = "/content/drive/MyDrive/Project Dataset/lyrics_generated"

OUT_DIR     = "/content/drive/MyDrive/hard_task_results"
os.makedirs(OUT_DIR, exist_ok=True)
LATVIS_DIR  = os.path.join(OUT_DIR, "latent_visualization")
RECON_DIR   = os.path.join(OUT_DIR, "reconstructions")
os.makedirs(LATVIS_DIR, exist_ok=True)
os.makedirs(RECON_DIR, exist_ok=True)

print("AUDIO_ROOT exists?", os.path.isdir(AUDIO_ROOT), AUDIO_ROOT)
print("LYRICS_ROOT exists?", os.path.isdir(LYRICS_ROOT), LYRICS_ROOT)
print("OUT_DIR:", OUT_DIR)

#Build Paired Index (Audio & Lyrics) + Labels
import glob
import numpy as np
import pandas as pd

def build_paired_index(audio_root, lyrics_root, max_files_per_genre=None, max_files_total=None):
    genre_dirs = sorted([d for d in glob.glob(os.path.join(audio_root, "*")) if os.path.isdir(d)])
    rows = []
    for gdir in genre_dirs:
        genre = os.path.basename(gdir)
        wavs = sorted(glob.glob(os.path.join(gdir, "*.wav")))
        if max_files_per_genre is not None:
            wavs = wavs[:max_files_per_genre]
        for wav in wavs:
            track_id = os.path.splitext(os.path.basename(wav))[0]
            lpath = os.path.join(lyrics_root, genre, f"{track_id}.txt")
            rows.append((genre, track_id, wav, lpath if os.path.exists(lpath) else None))

    df = pd.DataFrame(rows, columns=["genre","track_id","audio_path","lyrics_path"])
    if max_files_total is not None and len(df) > max_files_total:
        df = df.sample(n=max_files_total, random_state=42).reset_index(drop=True)

    coverage = df["lyrics_path"].notna().mean() * 100
    print(f"Tracks={len(df)} | Genres={df['genre'].nunique()} | Lyrics coverage={coverage:.1f}%")
    return df

MAX_FILES_PER_GENRE = None
MAX_FILES_TOTAL = None

df = build_paired_index(AUDIO_ROOT, LYRICS_ROOT, MAX_FILES_PER_GENRE, MAX_FILES_TOTAL)

genres = sorted(df["genre"].unique().tolist())
genre_to_id = {g:i for i,g in enumerate(genres)}
id_to_genre = {i:g for g,i in genre_to_id.items()}
Y = np.array([genre_to_id[g] for g in df["genre"]], dtype=np.int64)

df.to_csv(os.path.join(OUT_DIR, "paired_index.csv"), index=False)
df.head()

# Audio features (fixed-size log-mel spectograms)
import librosa

SR = 22050
DURATION = 30.0
N_MELS = 64
N_FFT = 1024
HOP = 512

TARGET_SAMPLES = int(SR * DURATION)
TARGET_FRAMES = 1 + TARGET_SAMPLES // HOP

def logmel_fixed(wav_path):
    y, _ = librosa.load(wav_path, sr=SR, mono=True)
    if len(y) < TARGET_SAMPLES:
        y = np.pad(y, (0, TARGET_SAMPLES - len(y)))
    else:
        y = y[:TARGET_SAMPLES]

    mel = librosa.feature.melspectrogram(
        y=y, sr=SR, n_fft=N_FFT, hop_length=HOP, n_mels=N_MELS, power=2.0
    )
    logmel = librosa.power_to_db(mel, ref=np.max).astype(np.float32)  # (M, T)

    if logmel.shape[1] < TARGET_FRAMES:
        logmel = np.pad(logmel, ((0,0),(0, TARGET_FRAMES-logmel.shape[1])), mode="constant")
    else:
        logmel = logmel[:, :TARGET_FRAMES]
    return logmel

def estimate_audio_norm(df, max_items=300):
    idxs = np.arange(len(df))
    if len(df) > max_items:
        np.random.seed(42)
        idxs = np.random.choice(idxs, size=max_items, replace=False)
    mats = np.stack([logmel_fixed(df.loc[i, "audio_path"]) for i in idxs], axis=0)
    return float(mats.mean()), float(mats.std() + 1e-6)

AUDIO_MEAN, AUDIO_STD = estimate_audio_norm(df, max_items=300)
print("Audio mean/std:", AUDIO_MEAN, AUDIO_STD)

# Lyrics Embeddings (Sentence Transformer)
from sentence_transformers import SentenceTransformer

TEXT_MODEL_NAME = "all-MiniLM-L6-v2"
text_model = SentenceTransformer(TEXT_MODEL_NAME)

def read_text(path):
    if path is None:
        return ""
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read().strip()

texts = [read_text(p) for p in df["lyrics_path"].tolist()]
E = text_model.encode(texts, batch_size=64, show_progress_bar=True, convert_to_numpy=True).astype(np.float32)

np.save(os.path.join(OUT_DIR, "lyrics_embeddings.npy"), E)
print("Lyrics embeddings:", E.shape)

# Dataset/Dataloader
import torch
from torch.utils.data import Dataset, DataLoader

class HardDataset(Dataset):
    def __init__(self, df, E, Y, audio_mean, audio_std):
        self.df = df.reset_index(drop=True)
        self.E = E
        self.Y = Y
        self.audio_mean = audio_mean
        self.audio_std = audio_std

    def __len__(self): return len(self.df)

    def __getitem__(self, i):
        x = logmel_fixed(self.df.loc[i, "audio_path"])
        x = (x - self.audio_mean) / self.audio_std
        x = torch.tensor(x[None, :, :], dtype=torch.float32)  # (1,M,T)

        e = torch.tensor(self.E[i], dtype=torch.float32)
        y = torch.tensor(self.Y[i], dtype=torch.long)
        return x, e, y

ds = HardDataset(df, E, Y, AUDIO_MEAN, AUDIO_STD)
dl = DataLoader(ds, batch_size=16, shuffle=True, num_workers=2, pin_memory=True)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE)

# CVAE model (audio + lyrics + genre) with Beta-VAE loss
import torch.nn as nn
import torch.nn.functional as F

class ConvEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(1, 16, 3, stride=2, padding=1), nn.ReLU(),
            nn.Conv2d(16, 32, 3, stride=2, padding=1), nn.ReLU(),
            nn.Conv2d(32, 64, 3, stride=2, padding=1), nn.ReLU(),
            nn.Conv2d(64, 128, 3, stride=2, padding=1), nn.ReLU(),
        )
    def forward(self, x): return self.net(x)

class ConvDecoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.ConvTranspose2d(128, 64, 4, stride=2, padding=1), nn.ReLU(),
            nn.ConvTranspose2d(64, 32, 4, stride=2, padding=1), nn.ReLU(),
            nn.ConvTranspose2d(32, 16, 4, stride=2, padding=1), nn.ReLU(),
            nn.ConvTranspose2d(16, 1, 4, stride=2, padding=1),
        )
    def forward(self, h): return self.net(h)

class CVAE_MultiModal(nn.Module):
    def __init__(self, n_genres, lyrics_dim, n_mels, t_frames, latent_dim=16, cond_dim=32):
        super().__init__()
        self.latent_dim = latent_dim
        self.cond_dim = cond_dim

        self.genre_emb = nn.Embedding(n_genres, cond_dim)

        self.enc_conv = ConvEncoder()
        with torch.no_grad():
            dummy = torch.zeros(1, 1, n_mels, t_frames)
            h = self.enc_conv(dummy)
            self.h_shape = h.shape[1:]
            self.h_dim = int(np.prod(self.h_shape))

        self.audio_fc = nn.Linear(self.h_dim, 256)

        self.lyrics_mlp = nn.Sequential(
            nn.Linear(lyrics_dim, 256), nn.ReLU(),
            nn.Linear(256, 128), nn.ReLU(),
        )

        self.fuse = nn.Sequential(
            nn.Linear(256 + 128 + cond_dim, 256), nn.ReLU(),
        )
        self.fc_mu = nn.Linear(256, latent_dim)
        self.fc_logvar = nn.Linear(256, latent_dim)

        # Decoder: reconstruct audio
        self.dec_fc = nn.Sequential(
            nn.Linear(latent_dim + cond_dim, 256), nn.ReLU(),
            nn.Linear(256, self.h_dim), nn.ReLU(),
        )
        self.dec_conv = ConvDecoder()

        # Decoder head: predict lyrics embedding (multi-modal reconstruction)
        self.lyrics_head = nn.Sequential(
            nn.Linear(latent_dim + cond_dim, 256), nn.ReLU(),
            nn.Linear(256, lyrics_dim),
        )

    def encode(self, x, e, y):
        h = self.enc_conv(x).view(x.size(0), -1)
        a = torch.relu(self.audio_fc(h))
        l = self.lyrics_mlp(e)
        c = self.genre_emb(y)
        f = self.fuse(torch.cat([a, l, c], dim=1))
        return self.fc_mu(f), self.fc_logvar(f)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z, y):
        c = self.genre_emb(y)
        zy = torch.cat([z, c], dim=1)

        hflat = self.dec_fc(zy)
        h = hflat.view(z.size(0), *self.h_shape)
        x_hat = self.dec_conv(h)

        e_hat = self.lyrics_head(zy)
        return x_hat, e_hat

    def forward(self, x, e, y):
        mu, logvar = self.encode(x, e, y)
        z = self.reparameterize(mu, logvar)
        x_hat, e_hat = self.decode(z, y)
        return x_hat, e_hat, mu, logvar

def cvae_loss(x, x_hat, e, e_hat, mu, logvar, beta=4.0, lambda_lyrics=0.2):
    x_hat = x_hat[:, :, :x.shape[2], :x.shape[3]]

    recon_audio = F.mse_loss(x_hat, x, reduction="mean")
    recon_lyrics = F.mse_loss(e_hat, e, reduction="mean")
    kld = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())

    loss = recon_audio + lambda_lyrics * recon_lyrics + beta * kld
    return loss, recon_audio, recon_lyrics, kld

#Train CVAE (Beta-VAE style) + extract latents
import torch
from tqdm import tqdm

model = CVAE_MultiModal(
    n_genres=len(genres),
    lyrics_dim=E.shape[1],
    n_mels=N_MELS,
    t_frames=TARGET_FRAMES,
    latent_dim=16,
    cond_dim=32
).to(DEVICE)

opt = torch.optim.Adam(model.parameters(), lr=1e-3)

EPOCHS = 50
BETA = 3.0
LAMBDA_LYRICS = 0.2

history = []
model.train()
for ep in range(1, EPOCHS+1):
    tot = ra = rl = kld = 0.0
    n = 0
    for xb, eb, yb in dl:
        xb, eb, yb = xb.to(DEVICE), eb.to(DEVICE), yb.to(DEVICE)

        x_hat, e_hat, mu, logvar = model(xb, eb, yb)
        loss, recon_a, recon_l, k = cvae_loss(
            xb, x_hat, eb, e_hat, mu, logvar,
            beta=BETA, lambda_lyrics=LAMBDA_LYRICS
        )

        opt.zero_grad()
        loss.backward()
        opt.step()

        bs = xb.size(0)
        n += bs
        tot += loss.item() * bs
        ra += recon_a.item() * bs
        rl += recon_l.item() * bs
        kld += k.item() * bs

    history.append({
        "epoch": ep,
        "loss": tot/n,
        "recon_audio": ra/n,
        "recon_lyrics": rl/n,
        "kld": kld/n
    })
    if ep % 10 == 0 or ep == 1:
        print(f"Epoch {ep:02d} | loss={tot/n:.4f} ra={ra/n:.4f} rl={rl/n:.4f} kld={kld/n:.4f}")

pd.DataFrame(history).to_csv(os.path.join(OUT_DIR, "cvae_train_history.csv"), index=False)

# Latent extraction (use mu)
model.eval()
Z = []
with torch.no_grad():
    for xb, eb, yb in DataLoader(ds, batch_size=32, shuffle=False):
        mu, _ = model.encode(xb.to(DEVICE), eb.to(DEVICE), yb.to(DEVICE))
        Z.append(mu.cpu().numpy())
Z = np.concatenate(Z, axis=0)
np.save(os.path.join(OUT_DIR, "latent_mu.npy"), Z)
print("Z:", Z.shape)

#Clustering + Hard-task metrics (Silhouette, NMI, ARI, Purity)
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, adjusted_rand_score, normalized_mutual_info_score

def cluster_purity(y_true, y_pred):
    # purity = sum_k max_j |Ck ∩ Tj| / N
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    total = 0
    for c in np.unique(y_pred):
        idx = np.where(y_pred == c)[0]
        if len(idx) == 0:
            continue
        counts = np.bincount(y_true[idx])
        total += counts.max()
    return total / len(y_true)

Zs = StandardScaler().fit_transform(Z)
k = len(genres)

pred = KMeans(n_clusters=k, random_state=42, n_init="auto").fit_predict(Zs)

metrics = {
    "method": "CVAE(beta)+KMeans",
    "k": k,
    "silhouette": float(silhouette_score(Zs, pred)),
    "NMI": float(normalized_mutual_info_score(Y, pred)),
    "ARI": float(adjusted_rand_score(Y, pred)),
    "purity": float(cluster_purity(Y, pred)),
}
metrics_df = pd.DataFrame([metrics])
metrics_df.to_csv(os.path.join(OUT_DIR, "hard_metrics_cvae.csv"), index=False)
metrics_df

#Baselines required in Hard task (PCA+KMeans, AE+KMeans, direct spectral)
from sklearn.decomposition import PCA

# Direct spectral feature clustering: pooled log-mel only
def audio_pooled_logmel(df):
    feats = []
    for p in df["audio_path"].tolist():
        X = logmel_fixed(p)  # (M,T)
        feats.append(np.concatenate([X.mean(axis=1), X.std(axis=1)], axis=0))  # (2M,)
    return np.stack(feats, axis=0).astype(np.float32)

A_pool = audio_pooled_logmel(df)
E_lyr = E.astype(np.float32)

A_std = StandardScaler().fit_transform(A_pool)
E_std = StandardScaler().fit_transform(E_lyr)
H = np.concatenate([A_std, E_std], axis=1)  # simple hybrid vector for baselines

# Baseline 1: PCA + KMeans
H_pca = PCA(n_components=Z.shape[1], random_state=42).fit_transform(H)
H_pca_s = StandardScaler().fit_transform(H_pca)
pred_pca = KMeans(n_clusters=k, random_state=42, n_init="auto").fit_predict(H_pca_s)

# Baseline 2: Autoencoder + KMeans (MLP AE on H)
import torch.nn as nn
import torch.nn.functional as F
import torch

class MLP_AE(nn.Module):
    def __init__(self, input_dim, latent_dim=16, hidden=256):
        super().__init__()
        self.enc = nn.Sequential(nn.Linear(input_dim, hidden), nn.ReLU(),
                                 nn.Linear(hidden, latent_dim))
        self.dec = nn.Sequential(nn.Linear(latent_dim, hidden), nn.ReLU(),
                                 nn.Linear(hidden, input_dim))
    def forward(self, x):
        z = self.enc(x)
        xh = self.dec(z)
        return xh, z

Xh = torch.tensor(H, dtype=torch.float32)
ae = MLP_AE(input_dim=H.shape[1], latent_dim=Z.shape[1]).to(DEVICE)
opt_ae = torch.optim.Adam(ae.parameters(), lr=1e-3)

ae.train()
for ep in range(1, 51):
    idx = torch.randperm(Xh.size(0))
    for i in range(0, Xh.size(0), 256):
        xb = Xh[idx[i:i+256]].to(DEVICE)
        xhat, z = ae(xb)
        loss = F.mse_loss(xhat, xb)
        opt_ae.zero_grad()
        loss.backward()
        opt_ae.step()
    if ep % 10 == 0 or ep == 1:
        print("AE epoch", ep, "loss", float(loss.detach().cpu()))

ae.eval()
with torch.no_grad():
    _, Z_ae = ae(Xh.to(DEVICE))
Z_ae = Z_ae.cpu().numpy()
Z_ae_s = StandardScaler().fit_transform(Z_ae)
pred_ae = KMeans(n_clusters=k, random_state=42, n_init="auto").fit_predict(Z_ae_s)

# Baseline 3: direct spectral features clustering (no PCA)
A_s = StandardScaler().fit_transform(A_pool)
pred_spec = KMeans(n_clusters=k, random_state=42, n_init="auto").fit_predict(A_s)

def metric_pack(name, X, labels):
    return {
        "method": name,
        "silhouette": float(silhouette_score(X, labels)),
        "NMI": float(normalized_mutual_info_score(Y, labels)),
        "ARI": float(adjusted_rand_score(Y, labels)),
        "purity": float(cluster_purity(Y, labels))
    }

baseline_rows = [
    metric_pack("BASELINE: PCA+KMeans", H_pca_s, pred_pca),
    metric_pack("BASELINE: AE+KMeans", Z_ae_s, pred_ae),
    metric_pack("BASELINE: DirectSpectral(KMeans)", A_s, pred_spec),
    metric_pack("MODEL: CVAE(beta)+KMeans", Zs, pred),
]
all_metrics_df = pd.DataFrame(baseline_rows)
all_metrics_df.to_csv(os.path.join(OUT_DIR, "hard_metrics_all_methods.csv"), index=False)
all_metrics_df

# Required visualizations (latent plots, cluster distribution, reconstructions)
import umap
import matplotlib.pyplot as plt

# UMAP latent plots
Z2 = umap.UMAP(n_components=2, n_neighbors=15, min_dist=0.1, random_state=42).fit_transform(Zs)

plt.figure(figsize=(7,6))
plt.scatter(Z2[:,0], Z2[:,1], c=pred, s=10, cmap="tab10")
plt.title("UMAP of CVAE latent (colored by predicted cluster)")
plt.tight_layout()
plt.savefig(os.path.join(LATVIS_DIR, "umap_latent_by_cluster.png"), dpi=200)
plt.close()

plt.figure(figsize=(7,6))
plt.scatter(Z2[:,0], Z2[:,1], c=Y, s=10, cmap="tab10")
plt.title("UMAP of CVAE latent (colored by true genre)")
plt.tight_layout()
plt.savefig(os.path.join(LATVIS_DIR, "umap_latent_by_genre.png"), dpi=200)
plt.close()

# Cluster distribution over genres (heatmap-like table plot)
ct = pd.crosstab(pd.Series(pred, name="cluster"), pd.Series(Y, name="genre_id"))
plt.figure(figsize=(10,4))
plt.imshow(ct.values, aspect="auto")
plt.yticks(range(ct.shape[0]), ct.index.tolist())
plt.xticks(range(ct.shape[1]), [id_to_genre[i] for i in ct.columns.tolist()], rotation=45, ha="right")
plt.colorbar(label="count")
plt.title("Cluster distribution over genres")
plt.tight_layout()
plt.savefig(os.path.join(LATVIS_DIR, "cluster_genre_distribution.png"), dpi=200)
plt.close()

print("Saved plots to:", LATVIS_DIR)

